<a href="https://colab.research.google.com/github/sarveshkodgule/DL-lab/blob/main/Exp_2_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# Scalar
a = tf.constant(10)

# Vector
b = tf.constant([1, 2, 3])

# Matrix
c = tf.constant([[1, 2], [3, 4]])

print("Scalar:", a)
print("Vector:", b)
print("Matrix:\n", c)

In [ ]:
x = tf.constant(10)
y= tf.constant(5)

print("Addition",tf.add (x,y))
print("Subtraction",tf.subtract( x,y))
print("Multiplication",tf.multiply (x,y))
print("division",tf.divide( x,y))


Addition tf.Tensor(15, shape=(), dtype=int32)
Subtraction tf.Tensor(5, shape=(), dtype=int32)
Multiplication tf.Tensor(50, shape=(), dtype=int32)
division tf.Tensor(2.0, shape=(), dtype=float64)


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([5,7,9])

result = tf.matmul(tf.expand_dims(x, axis=0), tf.expand_dims(y, axis=1))
print(result)

tf.Tensor([[46]], shape=(1, 1), dtype=int32)


In [ ]:
x = tf.constant([1,4,5,6,8,7])
result = tf.reshape(x,(2,3))
print(result)

tf.Tensor(
[[1 4 5]
 [6 8 7]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.constant([10, 20, 30, 40])

result = tf.reduce_mean(x)
print(result)

In [ ]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[5, 6],
                 [7, 8]])

In [ ]:
print(tf.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [ ]:
print(tf.subtract(a,b))

tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [ ]:
print(tf.multiply(a,b))

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]], dtype=tf.int32)


In [ ]:
b = tf.constant([[7, 8, 9],
                 [10, 11, 12]], dtype=tf.int32)


In [ ]:
print("\n1. Square:")
print(tf.square(a))



1. Square:
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


In [ ]:
print("\n1. SquareRoot:")
print(tf.sqrt(tf.cast(a, tf.float32)))


1. SquareRoot:
tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.2360678 2.4494896]], shape=(2, 3), dtype=float32)


In [ ]:
print("\n3. Power (Cube):")
print(tf.pow(a, 3))


3. Power (Cube):
tf.Tensor(
[[  1   8  27]
 [ 64 125 216]], shape=(2, 3), dtype=int32)


In [ ]:
print("\n4. Mean:")
print(tf.reduce_mean(tf.cast(a, tf.float32)))



4. Mean:
tf.Tensor(3.5, shape=(), dtype=float32)


In [ ]:
print("\n5. Sum:")
print(tf.reduce_sum(a))



5. Sum:
tf.Tensor(21, shape=(), dtype=int32)


In [ ]:
print("\n6. Maximum:")
print(tf.reduce_max(a))


6. Maximum:
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
print("\n7. Minimum:")
print(tf.reduce_min(a))


7. Minimum:
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print("\n8. Reshape (3x2):")
print(tf.reshape(a, (3, 2)))


8. Reshape (3x2):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
print("\n9. Transpose:")
print(tf.transpose(a))



9. Transpose:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:

print("\n11. Stack:")
print(tf.stack([a, b]))


11. Stack:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
print("\n12. Slice (First 2 Rows, First 2 Columns):")
print(tf.slice(a, [0, 0], [2, 2]))


12. Slice (First 2 Rows, First 2 Columns):
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
# Create a 3D Tensor (Shape: 2 x 2 x 3)
a = tf.constant([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
], dtype=tf.int32)

b = tf.constant([
    [[13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24]]
], dtype=tf.int32)


In [ ]:
print("Tensor A:")
print(a)
print("Shape:", a.shape)

print("Tensor B:")
print(b)
print("Shape:", b.shape)


Tensor A:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Shape: (2, 2, 3)
Tensor B:
tf.Tensor(
[[[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(2, 2, 3), dtype=int32)
Shape: (2, 2, 3)


In [ ]:
print("\n2. Square Root")
print(tf.sqrt(tf.cast(a, tf.float32)))

print(" Power (Cube)")
print(tf.pow(a, 3))

print("Mean")
print(tf.reduce_mean(tf.cast(a, tf.float32)))

print("Sum")
print(tf.reduce_sum(a))

print("Maximum")
print(tf.reduce_max(a))



2. Square Root
tf.Tensor(
[[[1.        1.4142135 1.7320508]
  [2.        2.2360678 2.4494896]]

 [[2.6457512 2.828427  3.       ]
  [3.1622777 3.3166246 3.4641016]]], shape=(2, 2, 3), dtype=float32)
 Power (Cube)
tf.Tensor(
[[[   1    8   27]
  [  64  125  216]]

 [[ 343  512  729]
  [1000 1331 1728]]], shape=(2, 2, 3), dtype=int32)
Mean
tf.Tensor(6.5, shape=(), dtype=float32)
Sum
tf.Tensor(78, shape=(), dtype=int32)
Maximum
tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
print("\n1. Addition (A + B)")
print(tf.add(a, b))

print("Subtraction (A - B)")
print(tf.subtract(a, b))

print("\n3. Multiplication (A × B)")
print(tf.multiply(a, b))

print("\n4. Division (A ÷ B)")
print(tf.divide(a, b))


1. Addition (A + B)
tf.Tensor(
[[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]], shape=(2, 2, 3), dtype=int32)

2. Subtraction (A - B)
tf.Tensor(
[[[-12 -12 -12]
  [-12 -12 -12]]

 [[-12 -12 -12]
  [-12 -12 -12]]], shape=(2, 2, 3), dtype=int32)

3. Multiplication (A × B)
tf.Tensor(
[[[ 13  28  45]
  [ 64  85 108]]

 [[133 160 189]
  [220 253 288]]], shape=(2, 2, 3), dtype=int32)

4. Division (A ÷ B)
tf.Tensor(
[[[0.07692308 0.14285714 0.2       ]
  [0.25       0.29411765 0.33333333]]

 [[0.36842105 0.4        0.42857143]
  [0.45454545 0.47826087 0.5       ]]], shape=(2, 2, 3), dtype=float64)


In [ ]:
print("\n13. Indexing")
print("First Matrix:")
print(a[0])

print("\nFirst Row of First Matrix:")
print(a[0, 0])


13. Indexing
First Matrix:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

First Row of First Matrix:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
# problem 1
import tensorflow as tf


In [ ]:
scalar = tf.constant(25)
print("Scalar Tensor:")
print(scalar)
print("Shape:", scalar.shape)
print()

vector = tf.constant([5, 10, 15, 20])
print("Vector Tensor:")
print(vector)
print("Shape:", vector.shape)
print()

matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print("2 × 3 Matrix:")
print(matrix)
print("Shape:", matrix.shape)
print()

tensor3d = tf.constant([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]]
])
print("3 × 3 × 2 Tensor:")
print(tensor3d)
print("Shape:", tensor3d.shape)

Scalar Tensor:
tf.Tensor(25, shape=(), dtype=int32)
Shape: ()

Vector Tensor:
tf.Tensor([ 5 10 15 20], shape=(4,), dtype=int32)
Shape: (4,)

2 × 3 Matrix:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)

3 × 3 × 2 Tensor:
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]], shape=(3, 3, 2), dtype=int32)
Shape: (3, 3, 2)


In [ ]:
# problem 2

tensor = tf.constant([[2, 4, 6],
                      [8, 10, 12]])


In [ ]:
print("Tensor")
print(tensor)

Tensor
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
print("Shape:", tensor.shape)
print("Rank:", tf.rank(tensor))
print("Data Type:", tensor.dtype)
print("Number of Elements:", tf.size(tensor))

Shape: (2, 3)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Data Type: <dtype: 'int32'>
Number of Elements: tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# problem 3
import tensorflow as tf

# Create matrices
A = tf.constant([[2, 4],
                 [6, 8]])

B = tf.constant([[1, 3],
                 [5, 7]])

# Addition
add = tf.add(A, B)

# Subtraction
sub = tf.subtract(A, B)

print("Addition:\n", add)
print("Subtraction:\n", sub)

Addition:
 tf.Tensor(
[[ 3  7]
 [11 15]], shape=(2, 2), dtype=int32)
Subtraction:
 tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [ ]:
# problem 4
# Create matrices
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf.constant([[5, 6],
                 [7, 8]])

# Matrix Multiplication
result = tf.matmul(A, B)

print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
# problem 5
# Create matrices
A = tf.constant([[2, 3],
                 [4, 5]])

B = tf.constant([[6, 7],
                 [8, 9]])

# Element-wise Multiplication
result = tf.multiply(A, B)

print("Element-wise Multiplication:\n", result)

Element-wise Multiplication:
 tf.Tensor(
[[12 21]
 [32 45]], shape=(2, 2), dtype=int32)


In [ ]:
# problem 6
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])

tensor_2x4 = tf.reshape(tensor, (2, 4))

tensor_4x2 = tf.reshape(tensor, (4, 2))

tensor_2x2x2 = tf.reshape(tensor, (2, 2, 2))

print("Original Tensor:")
print(tensor)

print("(2 x 4):")
print(tensor_2x4)

print("(4 x 2):")
print(tensor_4x2)

print("(2 x 2 x 2):")
print(tensor_2x2x2)

Original Tensor:
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
(2 x 4):
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
(4 x 2):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
(2 x 2 x 2):
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
#  problem 7
tensor = tf.constant([[5, 10, 15],
                      [20, 25, 30]])
print("Tensor:")
print(tensor)
print("Sum:", tf.reduce_sum(tensor))
print("Mean:", tf.reduce_mean(tf.cast(tensor, tf.float32)))
print("Maximum Value:", tf.reduce_max(tensor))
print("Minimum Value:", tf.reduce_min(tensor))


Tensor:
tf.Tensor(
[[ 5 10 15]
 [20 25 30]], shape=(2, 3), dtype=int32)
Sum: tf.Tensor(105, shape=(), dtype=int32)
Mean: tf.Tensor(17.5, shape=(), dtype=float32)
Maximum Value: tf.Tensor(30, shape=(), dtype=int32)
Minimum Value: tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# problem 9
zeros = tf.zeros((3, 3))
ones = tf.ones((4, 2))
identity = tf.eye(4)
print("3 x 3 Zeros Tensor:")
print(zeros)

print("\n4 x 2 Ones Tensor:")
print(ones)

print("\nIdentity Matrix (4 x 4):")
print(identity)

3 x 3 Zeros Tensor:
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

4 x 2 Ones Tensor:
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]], shape=(4, 2), dtype=float32)

Identity Matrix (4 x 4):
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
